Develop pc bv1.0 mme301
lardc/hw-MXUControlBoard pull request #2
Opened 2022-12-28 08:18 UTC by nonphixi0n

2023-01-11 11:27 UTC, asytyi requested changes

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/Commutator.c
> +				if (REG_MEASUREMENT_POSITION == 1)
Здесь и далее вместо
`if (REG_MEASUREMENT_POSITION == 1)`
надо
`if (DataTable[REG_MEASUREMENT_POSITION] == 1)`

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +uint8_t Data_Length = 4;
Выбранный способ формирования отладочных функций является неудачным. В итоге эти функции дублируют таблицу коммутации. Например, при изменении платы надо помнить, что потребуется внесение изменений в двух местах. При этом сами отладочные функции лишены гибкости.
Будет правильнее сделать, например, две отладочные функции которые умеют следующее:

1. Функция, которая считывает из отладочного регистра номер из таблицы коммутации. И для этого номера можно подать или снять высокий уровень (включить/выключить реле)
2. Функция, которая считывает из отладочного регистра номер регистра и маску. И записывает в сдвиговый регистр с соответствующим номером заданную маску.

Это гибкий подход, который позволит при необходимости пошагово всё проверить.

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +//-----------------------
Такие обёртки не несут особого смысла и только перегружают код. Почему нельзя просто использовать `LL_SPITurnOnOE` и какую ценность даёт `DBACT_SPITurnOnOE`? Именно здесь посоветую не загружать код обёрточными функциями и их объявлениями.

При этом глобально я обёртки ценю и уважаю, но когда они несут смысл. Например, если есть функция `SetPort1(true)`  оборачивается в какую-нибудь `TurnOnIndication()`. Вопросов нет, читаемость улучшилась.

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/Global.h
> +#define COMM_DELAY_LONG_MS						500
Копипасту убрать, задержку поправить до адекватного значения

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_SELF_TEST_ACTIVE			2	// Флаг состояния системы самотестирования
Почему этот регистр находится в области NVRAM?

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/SelfTest.c
> +			ST_State = 1;
Абсолютно лишняя сущность. Объяви в функции переменную
`static DeviceSubState PrevSubstate = SS_None`
а в кейсах включения коммутации обновляешь её, например
`PrevSubstate  = SS_ST_InputRelayCheck_1`

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +	// return (Error >= DataTable[REG_SFTST_V_ALLOWED_ERR]) ? false : true;
Закомментированный код коммитить запрещено

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/Logic.c
> +	MeasurementPosition = DataTable[REG_MEASUREMENT_POSITION];
Ето что и для чего? Переменная нигде не используется. Вообще можно прибить эту либу, а функции перенести в Controller, если нужны

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +	return false;
Неудачная реализация функции. Нормально отработает, если будет вызвана по истечению таймаута. Если цикл проверки по каким-то причинам будет прерван, то следующее выставление таймаута будет косячным. Именно здесь в коде возможно такого не будет. Но не факт, что в дальнейшем не появится такой функционал, или реализация будет скопирована в проект, где это важно. Поэтому сразу надо делать правильно. А правильно вот так:

В `void CONTROL_LogicProcess()` объявляешь переменную
`static Int64U Delay = 0`
и в свиче инициализацию и проверку задержки делаешь в отдельных кейсах, т.е.
```
switch(CONTROL_SubState)
{
	case SS_StartUp:
		Delay = CONTROL_TimeCounter + DataTable[REG_PS_FIRST_START_TIME]
		CONTROL_SetDeviceState(DS_InProcess, SS_WaitDelay);
		break;
	
	case SS_WaitDelay:
		if(CONTROL_TimeCounter > Delay)
			....
		break;
```

Будет работать железобетонно в любых случаях.

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +					CONTROL_SetDeviceState(DS_InProcess, SS_Commutation);
Как будто `DS_SelfTest` и `DS_InProcess` дублируют друг друга.
Непосредственно включение коммутации для измерения прибора является синхронным процессом. Т.е. поступает команда на включение коммутации (я имею ввиду команды 100-110) и она быстро исполняется в самом обработчике.
Длительным процессом является только селф тест. Ну вот надо оставить из девайс стейтов только 
`DS_InProcess` в рамках которого обрабатываются сабстейты.

2023-01-11 11:27 UTC, asytyi commented on Firmware/Source/Controller/Commutator.c
> +void COMM_Commutate(Int16U ActionID)
Функция нигде не вызывается

2023-02-07 10:23 UTC, asytyi requested changes
Есть замечания

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_SELF_TEST_ACTIVE			130	// Флаг состояния системы самотестирования
Если `REG_SELF_TEST_ACTIVE` статусный регистр, то его надо поместить в read-only область, т.е. регистры, которые начинаются от 192. 192-197 стандартные регистры состояния, их не трогать)
А вот `REG_SFTST_V_ALLOWED_ERR` зря перенёс. Уровень ошибки будет единожды настраиваться при запуске блока, и ВУ ничего не будет в этом плане задавать. Поэтому место ему в NVRAM области, где он и был

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> -#define REG_SFTST_V_ALLOWED_ERR			0	// Допустимая погрешность измеренного значения напряжения (%)
Надо выровнять табуляции, чтобы все числовые значения шли в один ряд

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.h
> +void ZcRD_OutputValuesReset1();
Это что за чудо?

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
>  #define ACT_COMM_ILEAK_GATE_EMITTER_POS_PULSE	101 // Режим измерения тока утечки затвора-эмиттера (положительный импульс)
Сейчас обратил внимание. Заряд затвора измеряется при единственной коммутации. Поэтому `ACT_COMM_Q_GATE_NEG_PULSE` надо выпилить, а `ACT_COMM_Q_GATE_POS_PULSE` переименовать в `ACT_COMM_Q_GATE`

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +		//DELAY_MS(1);
Закомментированный код убрать

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +void ZcRD_OutputValuesReset1()
Мёртвый код убрать

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	uint8_t Data_Lenght = 14;
Магических чисел быть не должно. 14 вынести в осмысленный дефайн. Лучше всего сделать отдельные дефайны по числу регистров на каждой плате, например
```
#define NUM_REGS_INPUT_BOARD 1
#define NUM_REGS_HV_BOARD 3
```
а затем дефайн общего числа регситров и его использовать
```
#define NUM_REGS_TOTAL    (NUM_REGS_INPUT_BOARD + NUM_REGS_HV_BOARD)
```
Читаемость кода сильно улучшится

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_SELF_TEST_ACTIVE			130	// Флаг состояния системы самотестирования
Кстати, вместо регистра REG_SFTST_V_ALLOWED_ERR  в коде в SelfTest.c используется дефайн. Нужно всё-таки регистр

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/SelfTest.c
> +			PrevSubstate = SS_None;
Здесь и далее исправить присвоение PrevSubstate как описано в треде в слэке

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/SelfTest.c
>  		case SS_ST_CurrentMeasure:
В операторе
```
if (Error >= ST_V_ALLOWED_ERR_DEF)
{
	DataTable[REG_SELF_TEST_OP_RESULT] = OPRESULT_FAIL;
	CONTROL_SwitchToFault(DF_VOLTAGE_MEASURING);
}
```
добавь статусный регистр в который будет записываться значение PrevSubstate. Это позволит определять на каком шаге произошёл фэйл.

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/LowLevel.c
> +	DELAY_MS(1);
Не велика ли задержка в 1мс для сброса? Как будто достаточно в тысячу раз меньше `DELAY_US(1);`

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/Global.h
> +#define ADC_V_CC								150.0f	// Напряжение при замкнутой цепи (в В)
Напряжение в вольтах?

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				break;
Вместо этого достаточно написать
```
    default:
        break;
```

2023-02-07 10:23 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				}
Здесь происходит что-то непонятное. `CONTROL_TimeCounter` уже объявлена и является глобальным счётчиком, который инкрементируется в прерывании. Зачем она здесь как статик объявляется? Код второго кейса должен выглядеть вот так
```
			case SS_WaitDelay:
				if (CONTROL_TimeCounter >= Delay)
					CONTROL_SetDeviceState(DS_InProcess, SS_WaitDelay);
				break;
```

2023-02-07 10:33 UTC, nonphixi0n commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_SELF_TEST_ACTIVE			130	// Флаг состояния системы самотестирования
Да, флаг режима самотестирования статусный. Перенес на 200. Регистр допустимой погрешности вернул, и в SelfTest.c убрал дефайн и выразил через DataTable.

2023-02-07 10:36 UTC, nonphixi0n commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> -#define REG_SFTST_V_ALLOWED_ERR			0	// Допустимая погрешность измеренного значения напряжения (%)
Поправил.

2023-02-07 10:36 UTC, nonphixi0n commented on Firmware/Source/Controller/ZcRegistersDriver.h
> +void ZcRD_OutputValuesReset1();
Блин, вчерашнее наследие от отладки. Убрад.

2023-02-07 10:39 UTC, nonphixi0n commented on Firmware/Source/Platform/DeviceObjectDictionary.h
>  #define ACT_COMM_ILEAK_GATE_EMITTER_POS_PULSE	101 // Режим измерения тока утечки затвора-эмиттера (положительный импульс)
Удалил лишнюю коммутацию.

2023-02-07 10:39 UTC, nonphixi0n commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +		//DELAY_MS(1);
Исправил.

2023-02-07 10:46 UTC, nonphixi0n commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	uint8_t Data_Lenght = 14;
Добавил дефайны.

2023-02-07 10:46 UTC, nonphixi0n commented on Firmware/Source/Controller/SelfTest.c
> +			PrevSubstate = SS_None;
Сделал.

2023-02-07 10:51 UTC, nonphixi0n commented on Firmware/Source/Controller/SelfTest.c
>  		case SS_ST_CurrentMeasure:
Добавил регистр.

2023-02-07 10:52 UTC, nonphixi0n commented on Firmware/Source/Controller/LowLevel.c
> +	DELAY_MS(1);
Исправил.

2023-02-07 10:52 UTC, nonphixi0n commented on Firmware/Source/Controller/Global.h
> +#define ADC_V_CC								150.0f	// Напряжение при замкнутой цепи (в В)
В мв.

2023-02-07 10:59 UTC, nonphixi0n commented on Firmware/Source/Controller/Controller.c
> +				}
Здесь немного не понял. Сейчас сделал так, что при достижении счетчиком значения больше или равным задержке, сабстейт переходит в режим самотестирования.

2023-03-10 13:53 UTC, asytyi commented on Firmware/Source/Controller/Commutator.c
> +void COMM_PE()
Функцию лучше назвать `COMM_DisconnectPE()`

2023-03-10 13:53 UTC, asytyi commented on Firmware/Source/Controller/Global.h
> +#define ADC_V_CC								150.0f	// Напряжение при замкнутой цепи (в В)
Проверка связи. Уведомления об ответах приходят?

2023-03-10 13:55 UTC, asytyi commented on Firmware/Source/Controller/Global.h
> +#define ADC_V_CC								150.0f	// Напряжение при замкнутой цепи (в В)
@nonphixi0n и вот так

2023-03-10 13:55 UTC, nonphixi0n commented on Firmware/Source/Controller/Commutator.c
> +void COMM_PE()
Понял. Переименую

2023-03-10 14:29 UTC, nonphixi0n commented on Firmware/Source/Controller/Commutator.c
> +void COMM_PE()
Готово

2023-03-13 10:27 UTC, asytyi requested changes
Необходимо устранить замечания

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/Commutator.h
> +void COMM_PE();
`COMM_DisconnectPE()` используется в пределах библиотеки, поэтому внешнее объявление лишнее. Именно поэтому оно осталось незамеченным после правок

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/Commutator.c
> +					COMM_DisconnectPE();
`ZcRD_OutputValuesReset()` используется и до вызова `COMM_DisconnectPE()` и в нём самом. Такое неявное поведение лучше избегать. Лучше в `COMM_DisconnectPE()` вызов удалить и оставить только функции `ZcRD_OutputValuesCompose`

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +	if (Error <= 20)
Во-первых, этот код используется и в DebugActions, и в SelfTest, но с отличиями. Надо сделать одну функцию и её вызывать в двух местах, а не копипастить код.
Во-вторых, сам код какой-то замысловатый. Есть какая-то константа 150мВ, есть ошибка. Зачем так? Если известно падение напряжения при нормальном функционировании, то просто задай порог ошибочного напряжения, хранимого в регистре, и с ним сравнивай.
Например
```
bool TestVoltageFailed()
{
	return LL_SelfTestMeasure() > DataTable[REG_SFTST_V_ALLOWED_VOLTAGE];
}
```
просто и без излишеств.
Если нормальное напряжение 150мВ, то пусть в регистре будет 175-200мВ, например. Не знаю какой там разброс результатов.

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				//*pUserError = ERR_DEVICE_NOT_READY;
Ето что такое?

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				//*pUserError = ERR_DEVICE_NOT_READY;
Выше в `CONTROL_Idle` тоже закомментированный код. Дима, возьми за правило во время коммитов делать правый клик по коммитящимся файлам и просматривай изменения через Show Diff.
**Для всех изменённых файлов. Всегда.**
Чтобы не коммитить всякую непотребу

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/Global.h
>  #define COMM_DELAY_MS							1
По документации время переключения реле 8мс (фактическое поменьше). Почему ждём всего 1мс?

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/SelfTest.c
>  			}
Как я понимаю, процедура самотестирования в данный момент умеет только определять, что реле включаются и падение напряжение на них ниже определённого уровня. Но не умеет определять залипания.
Код не дорабатывать, обсудить в слэке.

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +		CurrentOutputValues[i] = 0;
Вылетел за границы массива. Если массив размера `NUM_REGS_TOTAL`, то проход по всем элементам
`for (i = 0; i < NUM_REGS_TOTAL; ++i)`

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	for (int i = 0; i <= (NUM_REGS_TOTAL - 1); i++)
Зачем создаётся копия массива?
- Придерживайся единого стиля объявления индексной переменной. У тебя она и в функции объявляется `int i;`, и потом локально в итерраторе массива `for (int i = 0; i <= (NUM_REGS_TOTAL - 1); i++)`
- В функциях выше для индекса используется `uint8_t`, здесь `int`, хотя массивы одинакового размера
- Лучше объявлять индекс в итераторе, а для прохода по всему массиву использовать  такую запись
`for (uint8_t i = 0; i < NUM_REGS_TOTAL; i++)`

Это всё мелочи, но из-за этих мелочей код выглядит непрофессионально и трудночитаемо

2023-03-13 10:27 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_FAULT_RELAY							129	// Faulty Relay
Этот регистр ведь только для чтения для верхнего уровня. Так почему он в записываемой области?

2023-03-13 10:29 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.c
> +uint8_t Data_Length = 4;
Не устранено, но если для отладки не требуется, то не настаиваю

2023-03-13 10:37 UTC, nonphixi0n commented on Firmware/Source/Controller/Commutator.h
> +void COMM_PE();
Сделано

2023-03-13 10:39 UTC, nonphixi0n commented on Firmware/Source/Controller/Commutator.c
> +					COMM_DisconnectPE();
Понятно, исправил

2023-03-13 10:54 UTC, nonphixi0n commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	for (int i = 0; i <= (NUM_REGS_TOTAL - 1); i++)
Сделано

2023-03-13 10:55 UTC, nonphixi0n commented on Firmware/Source/Controller/Global.h
>  #define COMM_DELAY_MS							1
Исправил

2023-03-13 10:55 UTC, nonphixi0n commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +		CurrentOutputValues[i] = 0;
Исправил

2023-03-13 10:58 UTC, nonphixi0n commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_FAULT_RELAY							129	// Faulty Relay
Саш, какой регистр ты имеешь в виду?

2023-03-13 11:07 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				break;
Здесь совсем ерунда:
1. `SS_InProcess` и `DS_InProcess` выглядят одинаково. Назови `SS_InProcess` каким-то более говорящим названием
2. `if(REG_SELF_TEST_OP_RESULT == 1)` сравнение не со значением регистра, а с его номером
3. Даже если исправить сравнение на значение регистра, то получается, если оно равно 1 (Кстати, 1 это что такое? Почему используется число, а не привязанный к нему дефайн?), то опять переходим к `CONTROL_SetDeviceState(DS_InProcess, SS_InProcess);`. Это же зацикливание.

2023-03-13 11:39 UTC, nonphixi0n commented on Firmware/Source/Controller/DebugActions.c
> +	if (Error <= 20)
Готово

2023-03-13 11:44 UTC, nonphixi0n commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	for (int i = 0; i <= (NUM_REGS_TOTAL - 1); i++)
Копию массива сделал для реверса самого массива

2023-03-13 11:45 UTC, nonphixi0n commented on Firmware/Source/Controller/Controller.c
> +				//*pUserError = ERR_DEVICE_NOT_READY;
Понял. Код исправил

2023-03-13 12:02 UTC, nonphixi0n commented on Firmware/Source/Controller/Controller.c
> +				break;
1. Исправил наименование

2023-03-13 12:45 UTC, asytyi commented on Firmware/Source/Controller/Commutator.h
> +void COMM_PE();
Стоп. Зачем ты переименовал `COMM_DisconnectPE()` в `COMM_СonnectPE()`? Разве эта функция включает землю? Она же подаёт высокий уровень на NC реле, что приводит отключению земли? Или я что-то неправильно понимаю?

2023-03-13 12:46 UTC, asytyi commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	for (int i = 0; i <= (NUM_REGS_TOTAL - 1); i++)
Объясни момент с реверсом. Может я что-то недопонял в коде

2023-03-13 12:48 UTC, nonphixi0n commented on Firmware/Source/Controller/Commutator.h
> +void COMM_PE();
Да, точно. Немного запутался. Переименовал обратно.

2023-03-15 12:09 UTC, nonphixi0n commented on Firmware/Source/Controller/ZcRegistersDriver.c
> +	for (int i = 0; i <= (NUM_REGS_TOTAL - 1); i++)
Потому что, у меня CommutationTable составлена в таком порядке: OutHVRealayBoard_1, OutHVRealayBoard_2, OutThermRelayBoard, InputRelayBoard. А подключение шлейфами в обратном: InputRelayBoard, OutThermRelayBoard, OutHVRealayBoard_2, OutHVRealayBoard_1.

2023-03-20 11:39 UTC, asytyi reviewed
В SelfTest добавлены массивы для тестирования на залипание InputRelay, но не добавлены для MCRelay

2023-10-16 09:38 UTC, closed without merging