Develop
lardc/hw-MXUControlBoard pull request #3
Opened 2023-10-23 09:25 UTC by IvanovDmtr

2023-10-30 14:42 UTC, asytyi requested changes

2023-10-30 14:42 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +	CONTROL_PMXU_CheckState();
В таком виде функция `CONTROL_PMXU_CheckState()` будет с максимально возможной интенсивностью опрашивать блок, занимая CAN-шину. Правильно будет выполнять опрос, когда это необходимо текущим состоянием блока MXU. И даже в этом случае опрашивать с каким-то разумным интервалом, чтобы ВУ или другие блоки тоже могли получить доступ к шине

2023-10-30 14:42 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +	PMXU_CheckWarning((Int16U *)&DataTable[REG_WARNING]);
В новых блоках мы не будем использовать регистр warning, т.к. он сообщает о каком-то аномальном поведении, но при этом не требует действий со стороны оператора или персонала. Потому что warning не блокирует дальнейшее функционирование.
В данном случае в PMXU warning использован для извещения о повышенном контактном сопротивлении, что неправильно. Если сопротивление настолько высоко, что фиксируется самодиагностикой, то установку эксплуатировать нельзя. Т.е. warning должен быть заменён на fault

2023-10-30 14:42 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
>  			break;
По новому алгоритму работы системы безопасности контур безопасности работает всегда, он не отключаем. И его срабатывание всегда приводит к сбросу реле. Единственное отличие, что при срабатывании из состояния `DS_SafetyActive` происходит смена состояния на `DS_SafetyTrig`. Во всех остальных случаях состояние не изменяется.

2023-10-30 14:42 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		case ACT_SELFT_TEST:
По идее самодиагностика должна запускаться при подаче питания. Эта команда может быть как отладочная, но ВУ о ней ничего не знает. Самодиагностику можно сделать отключаемой регистром EEPROM

2023-10-30 14:42 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				if(PMXU_Enable())
По хорошему в PMXU.c должен сразу стоять обработчик на всех функциях общения по CAN, который при возникновении сбоя по интерфейсу запишет подробности ошибки в регистры (функция `BHL_GetError`). А то сейчас при таймауте, юзер-ерроре и т.д. блок просто как будто будет игнорить команду `ACT_ENABLE_POWER` без каких-либо подробностей

2023-10-30 14:42 UTC, asytyi commented on Firmware/Source/Controller/SelfTest.c
> +				DataTable[REG_SELF_TEST_OP_RESULT] = OPRESULT_OK;
В процессе выполнения селфтеста промежуточное состояние надо хранить где-то в переменной, а не в регистре. Регистр это для внешних потребителей информации. А то из регистра будет вычитано, что тест ок, а он не ок и вообще в самом разгаре.
Т.е. при запуске теста оп-резалт надо ставить в `OPRESULT_NONE` и только после всех операций записывать результат `OPRESULT_OK` или `OPRESULT_FAIL`

2023-10-31 07:21 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
> +	PMXU_CheckWarning((Int16U *)&DataTable[REG_WARNING]);
Согласен и в таком случае строку с выставлением ворнинга я удаляю, т.к. сам PMXU должен выставлять у себя фолт, а не ворнинг

2023-10-31 07:40 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
>  			break;
Посмотри, правильно ли я тебя понял. Из кода удалил все вызовы, касающиеся отключения безопасности, но саму функцию нижнего уровня решил не удалять, вдруг в отладочных целях понадобиться.

2023-10-31 07:41 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
> +		case ACT_SELFT_TEST:
Вот раньше в LCTU так и было, например, потом решили, что будет ВУ иди MCU запускать селфтест и тут я сделал по аналогии с другими блоками. Если менять тут, то и в остальных блоках тоже надо будет.

2023-10-31 07:45 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
> +		case ACT_SELFT_TEST:
Сделал при вызове ACT_ENABLE_POWER

2023-10-31 08:01 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
> +				if(PMXU_Enable())
Сделал

2023-10-31 08:08 UTC, IvanovDmtr commented on Firmware/Source/Controller/SelfTest.c
> +				DataTable[REG_SELF_TEST_OP_RESULT] = OPRESULT_OK;
Да, там явная глупость была написана, не знаю, как так вышло. Исправил.

2023-11-01 09:38 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		case ACT_SELFT_TEST:
Как я понимаю селф-тест, он должен вызываться самим блоком при включении и давать опцию запуска по команде. В данный момент такая реализация ок. После пробной эксплуатации откорректируем, если что.

2023-11-01 09:41 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
>  			break;
Да, здесь всё ок. Отладочные функции могут оставаться.

2023-11-01 09:51 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +				CONTROL_SwitchToFault(DF_PMXU);
Эта реализация тоже нуждается в доработке. Пример из жизни. Перекрыли кран пневматики, давление в трубке всё ещё есть, PMXU считает, что всё ок. Перед вызовом коммутации MXU опрашивает блок, видит, что всё ок и включает коммутацию. Давление падает, блок фэйлится, MXU об этом не знает.
Может стоит опрашивать блок сразу после коммутации или с какой-то периодичностью, например, раз в 100-200мс, чтобы знать, что он ок, давление не упало и цилиндры в зажатом/отжатом состоянии.

2023-11-01 11:12 UTC, IvanovDmtr commented on Firmware/Source/Controller/Controller.c
> +				CONTROL_SwitchToFault(DF_PMXU);
Да, согласен. Про это не подумал. Добавил периодический опрос.

2023-11-07 13:15 UTC, asytyi approved these changes

2023-11-07 13:15 UTC, merged